openapi: 3.0.3
info:
  title: Argent Bank™ - OpenAPI 3.0
  description: |-
    API specification for the endpoints used to access the backend services of the Argent Bank™ website.
    This specification describes the enpoints implementing the accounts transactions API.
  contact:
    email: moolekick@gmail.com
  license:
    name: MIT
    url: https://mit-license.org/
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://192.168.1.26:3001/api/v1
tags:
  - name: transactions
    description: endpoints used to retrieve / update accounts transactions
paths:
  # ===================== list all transactions for account =====================
  /transactions/list:
    post:
      tags:
        - transactions
      summary: list all transactions for account
      description: retrieve all transactions on a given account for an authenticated user
      security:
        - bearer-auth: []
      # request
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              # account number
              type: object
              properties:
                accountNumber:
                  type: string
        required: true
      # responses
      responses:
        '200':
          description: Successfully retrieved transactions list
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/transactionListEntry"
        '400':
          description: Invalid request
        '401':
          description: Not authorized
        '404':
          description: Account not found
  # ======================== retrieve transaction details =======================
  /transactions/details:
    post:
      tags:
        - transactions
      summary: retrieve transaction details
      description: retrieve the details of a transaction on a given account for an authenticated user
      security:
        - bearer-auth: []
      # request
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              # account number, transaction id
              type: object
              properties:
                accountNumber:
                  type: string
                transactionId:
                  type: string
        required: true
      responses:
        '200':
          description: Successfully retrieved transaction details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transactionDetails'
        '400':
          description: Invalid request
        '401':
          description: Not authorized
        '404':
          description: Transaction not found

  # =========== update details for an existing transaction for account ==========
  /transactions/update:
    put:
      tags:
        - transactions
      summary: update details of an existing transaction
      description: update the details of an existing transaction on a given account for an authenticated user
      security:
        - bearer-auth: []
      # request
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/transactionDetailsUpdate"
        required: true
      # responses
      responses:
        '200':
          description: Successfully updated transaction
        '400':
          description: Invalid request
        '401':
          description: Not authorized
        '404':
          description: Account / transaction not found
components:
  securitySchemes:
    # authorization header
    bearer-auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: server-provided json web token
  schemas:
    # account transaction list entry
    transactionListEntry:
      type: object
      properties:
        transactionDate:
          type: string
          # UTC format regex validator
          pattern: '^\d{4}-\d{2}-\d{2}(\s|T)\d{2}:\d{2}:\d{2}\.\d{3}(Z)?$'
        transactionDescription:
          type: string
        # store value only since currency is stored at account level
        transactionAmount:
          type: number
        # store value only since currency is stored at account level
        transactionBalance:
          type: number
        # unique ID of the transaction
        transactionId:
          type: string
    # transaction details
    transactionDetails:
      type: object
      properties:
        transactionType:
          type: string
          enum:
            # restrict allowed values
            - Electronic
            - Wire transfer
        transactionCategory:
          type: string
          enum:
            # restrict allowed values
            - Food
            - Drink
            - Clothing
        transactionNotes:
          type: string
    # transaction details update
    transactionDetailsUpdate:
      type: object
      properties:
        accountNumber:
          type: string
        transactionId:
          type: string
        transactionCategory:
          type: string
          enum:
            # restrict allowed values
            - Food
            - Drink
            - Clothing
        transactionNotes:
          type: string